"""Initial schema.

Emitted from the SQLAlchemy metadata rather than hand-written DDL, so the schema
is correct for whichever dialect is connected — Postgres in production, SQLite
for a zero-dependency local run. Every migration after this one is a normal
autogenerated diff.

Revision ID: 0001
Create Date: 2026-08-03
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from app.models import Base

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from app.models import Base

    Base.metadata.drop_all(bind=op.get_bind())
